# Generated by Django 2.2.1 on 2020-07-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HighBlood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('sex', models.CharField(default='男', max_length=10)),
                ('tall', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('smoke', models.CharField(default='不吸', max_length=10)),
                ('drink', models.CharField(default='不喝酒', max_length=10)),
            ],
        ),
    ]
